// phrases.js
const phrases = [
  "A ripple of color hums under your fingertips.",
  "The crystal brightens with renewed vigor.",
  "Echoes of distant galaxies resonate within.",
  "Starlit currents surge through the prism.",
  "Your focus sculpts a new spectrum of light.",
  "The chamber sings as energy aligns.",
  "Vibrant arcs leap forth, eager to be shaped.",
  "A chorus of photons applauds your rhythm.",
  "The veil thins; radiant whispers guide you.",
  "Every pulse threads another story into the cosmos.",
  "The prism reflects your boundless ambition.",
  "Fractals bloom, unfolding luminous patterns.",
  "Time bends, letting more color seep through.",
  "Your intent becomes a beacon across realities.",
  "The resonant chord deepens with each strike.",
  "Luminescent particles swarm in celebration.",
  "Another breakthrough cascades through the spectrum.",
  "You are the maestro of this chromatic symphony.",
  "Essence trembles, awaiting your command.",
  "The crystal remembers every ascension.",
];
