// phrases.js
const phrases = [
  "The cube thunders with raw potential.",
  "A perfect edge gleams brighter than before.",
  "You hear the hum of distant fabrication lines.",
  "A neon pulse races across the cube's surface.",
  "Production metrics spike off the charts!",
  "A new alloy lattices inside the cube.",
  "Energy cascades like a waterfall of sparks.",
  "Diagnostics report: click efficiency +9000%.",
  "The cube reconfigures into a sharper shape.",
  "Vendors line up to buy whatever you're making.",
  "An automation crew salutes your leadership.",
  "Quantum residue twinkles in the air.",
  "You swear you heard the cube cheer.",
  "The factory floor vibrates with approval.",
  "Blueprints redraw themselves in your favor.",
  "A hyperlane courier delivers rare components.",
  "Heat signatures bloom like fireworks.",
  "Investment bots flood your account with credits.",
  "A prototype drones circles, impressed.",
  "Energy vaults overflow into fresh storage cells.",
  "An engineer yells, 'Keep that momentum going!'.",
  "Neon trails track your every decisive click.",
  "The cube flickers between dimensions briefly.",
  "A ripple of stardust charges the room.",
  "The automation wing chants your name in binary.",
  "Another production log hits a personal best.",
  "Liquid plasma boils with excitement.",
  "A rival tycoon calls to ask for tips.",
  "The cube shrugs off reality like loose paint.",
  "Forecast: infinite growth and rising profits.",
  "Sensors detect unstoppable hype.",
  "A cosmic investor nods in approval.",
  "Machinery syncs perfectly with your rhythm.",
  "Laser etchers fire in celebratory sequence.",
  "Replication bays push to overtime willingly.",
  "Chronal vaults send dividends from yesterday.",
  "Rift harvesters howl with extradimensional power.",
  "A combo meter in the sky flashes your stats.",
  "Finance bots debate if you're a myth.",
  "The cube's glow can be seen from orbit.",
  "You unlock a new playlist called 'Profit Thunder'.",
  "A scoreboard erupts with your leaderboard rank.",
  "The cube rotates to a never-before-seen angle.",
  "Factory morale surges into legendary territory.",
  "Supply lines bend to your will.",
  "A marketing drone composes a heroic ballad.",
  "Essence particles crowd around to get picked.",
  "Staging bay doors slam open with new shipments.",
  "Your fingers leave trails of superheated plasma.",
  "The cube whispers, 'More'.",
  "Warehouse bots high-five each other.",
  "An arcade scoreboard spells out your initials.",
  "The board of directors just applauded.",
  "An entire planet tunes in to watch you click.",
  "You feel the timeline bend toward prosperity.",
  "Every statistic leaps upward in unison.",
  "The energy grid requests your autograph.",
  "A pop-up reads: 'Efficiency Unlocked'.",
  "The void itself invests in your future.",
  "Cubic thunder echoes through the complex.",
  "The cube splits then snaps back, even stronger.",
  "A neon confetti storm rains down.",
  "A drone announces, 'Profit margin: ridiculous!'.",
  "Mechanics cheer as another upgrade slots in.",
  "A fresh mantra echoes: 'No such thing as idle'.",
  "You just outperformed the simulator's predictions.",
  "The cube releases a triumphant bass drop.",
  "A portal opens solely to watch the show.",
  "The command console flashes: 'UNREAL OUTPUT'.",
  "Every click sends ripples across the skyline.",
  "Stock charts are forced to add extra digits.",
  "The automation fleet paints your logo everywhere.",
  "A broadcast drones, 'Record profits secured!'.",
  "Time travelers stop by to invest early.",
  "The fabric of space gives you a thumbs up.",
  "A cascade of bonus loot pours from the cube.",
  "Even the idle counter clocks in for overtime.",
  "A sparkling voice says, 'Welcome to the big leagues'.",
  "Production servers start to glow red-hot.",
  "The energy surge cracks the sound barrier.",
  "You hit a combo so high it needs a permit.",
  "A holographic ticker tape parade begins.",
  "The cube flexes every flawless facet.",
  "Breaking news: Cube Forge conquers the charts.",
  "A rival conglomerate waves a white flag.",
  "Celestial accountants request your spreadsheet.",
  "The factory AI updates your title to 'Legend'.",
  "A triumphant synth chord rattles the rafters.",
  "Every gauge slams past maximum capacity.",
  "The cube's glow etches a mural in the air.",
  "Another epoch bows before your efficiency.",
  "Supply drones form a constellation of thanks.",
  "Essence sparkles, begging to be harvested.",
  "A new contract arrives stamped 'Top Priority'.",
  "The automation network whispers, 'Command us'.",
  "You feel reality calibrate around your ambition.",
  "Every click turns into a shooting star.",
  "A million simulations all agree: keep clicking.",
  "The cube syncs to the beat of your heartbeat.",
  "Ascension vaults whisper about your next leap.",
  "An inspector arrives and immediately resigns in awe.",
  "The cube projects profit graphs into the stars.",
  "You unlock a secret tab labeled 'Overdrive'.",
  "Forge sparks swirl into a miniature galaxy.",
  "A chorus of drones chants your motto.",
  "The automation grid hums a victory tune.",
  "You taste ozone and imminent growth.",
  "A rare achievement banner unfurls overhead.",
  "The cube radiates colors no spectrum can name.",
  "An intern faints from witnessing your combo count.",
  "Even the tutorial pops back in to applaud.",
  "The assembly line paints a mural of your cube.",
  "Space whales migrate just to watch the forge.",
  "You hear a whisper: 'Another upgrade awaits'.",
  "The timeline schedules extra room for your legacy.",
  "An achievement icon starts glowing in anticipation.",
  "Your essence reserves sparkle like bottled dawn.",
  "The cube purrs—yes, purrs—with contentment.",
];
